version: '3.1'

services:
  db:
    container_name: database-mysql-2
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_conf:/etc/mysql
    environment:
      MARIADB_ROOT_PASSWORD: testdb12345
    networks:
      - my_backend

  phpmyadmin:
    container_name: phpmyadmin-2
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1024M
      - MEMORY_LIMIT=1024M
      - MAX_EXECUTION_TIME=300
    networks:
      - my_backend
  api: 
    container_name: api
    image: phonepadithpp/api-express:0.6
    build:
      context: api
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 2000:2000
    networks:
      - my_backend
      - my_frontend
networks:
  my_backend:
    name: my_backend
  my_frontend:
    name: my_frontend
