apiVersion: v1
kind: Pod
metadata:
  name: test-redis
spec:
  containers:
    - image: redis:latest
      name: test-container
  volumes:
    - name: redis-persistent-storage
      persistentVolumeClaim:
        claimName: myclaim
