apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-02-24T12:22:18Z"
  generation: 1
  labels:
    app: web-proxy-2
  name: web-proxy-2
  namespace: tplus
  resourceVersion: "7787"
  uid: 9f7f4bf0-373d-427d-95de-d01aa3675d7c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-proxy-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-proxy-2
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}